### ISSUE TITLE
Error: 305 Oops! This server doesn't allow verification with alt accounts. Please use your main account to verify.

### ISSUE THREAD

**Issue by xiaozhang959** [shuttlenetwork/freegpt#2]
Hello, may I ask why I keep getting this prompt after I send /getkey for verification?
![图片](https://github.com/shuttleai/info/assets/89305607/96fa06a8-a581-41a2-9ba2-0b6238283bf2)

**Comment by tristandevs** [comment]
we switched to web dashboard
